"""Initial setup

Revision ID: a9fc3adff589
Revises: 
Create Date: 2026-08-19 16:56:42.994461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9fc3adff589'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_folder_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_folder_id'], ['folders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.create_index('uq_folder_user_parent_name', ['user_id', 'parent_folder_id', 'name'], unique=True, postgresql_where=sa.text('parent_folder_id IS NOT NULL'), sqlite_where=sa.text('parent_folder_id IS NOT NULL'))
        batch_op.create_index('uq_folder_user_root_name', ['user_id', 'name'], unique=True, postgresql_where=sa.text('parent_folder_id IS NULL'), sqlite_where=sa.text('parent_folder_id IS NULL'))

    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.drop_index('uq_folder_user_root_name', postgresql_where=sa.text('parent_folder_id IS NULL'), sqlite_where=sa.text('parent_folder_id IS NULL'))
        batch_op.drop_index('uq_folder_user_parent_name', postgresql_where=sa.text('parent_folder_id IS NOT NULL'), sqlite_where=sa.text('parent_folder_id IS NOT NULL'))

    op.drop_table('folders')
    op.drop_table('users')
    # ### end Alembic commands ###
